### PR TITLE
Fix no longer supported git PR refs

### LINKED ISSUE #287: Pull-Requests no longer working on BitBucket Server 7.0
### Your checklist for this issue

- [x] Jenkins version: 2.204.5

- [x] Plugin version: 2.7.0

- [ ] Bitbucket cloud

- [x] Bitbucket server and version: 7.0.0, 7.0.1

### Description

This plugin is no longer able to fetch and build pull-requests. Looks like thay changed the api without writing a note.

```
06:01:26  Started by user XXX YYY
06:01:26  Running as XXX YYY
06:01:34  ERROR: Could not do lightweight checkout, falling back to heavyweight
06:01:34  java.io.FileNotFoundException: URL: /rest/api/1.0/projects/proj/repos/repo/browse/Jenkinsfile?at=pull-requests%2F580%2Fmerge&start=0&limit=500
06:01:34  	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:831)
06:01:34  	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getFileContent(BitbucketServerAPIClient.java:1123)
06:01:34  	at com.cloudbees.jenkins.plugins.bitbucket.filesystem.BitbucketSCMFile.content(BitbucketSCMFile.java:98)
06:01:34  	at jenkins.scm.api.SCMFile.contentAsString(SCMFile.java:335)
06:01:34  	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:107)
06:01:34  	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:299)
06:01:34  	at hudson.model.ResourceController.execute(ResourceController.java:97)
06:01:34  	at hudson.model.Executor.run(Executor.java:427)
06:01:34  Checking out git https://xxx.yyyy.de/scm/proj/repo.git https://xxx.yyyy.de/scm/proj/repo.git into /var/jenkins_home/workspace/proj_repo_PR-580@script to read Jenkinsfile
06:01:34  using credential a63b7cb8-6690-4c0b-81b8-93969a0fabac
06:01:35  using credential a63b7cb8-6690-4c0b-81b8-93969a0fabac
06:01:35   > git rev-parse --is-inside-work-tree # timeout=10
06:01:35  Fetching changes from 2 remote Git repositories
06:01:35   > git config remote.origin.url https://xxx.yyyy.de/scm/proj/repo.git # timeout=10
06:01:35  Cleaning workspace
06:01:35   > git rev-parse --verify HEAD # timeout=10
06:01:35  No valid HEAD. Skipping the resetting
06:01:35   > git clean -ffdx # timeout=10
06:01:35  Pruning obsolete local branches
06:01:35  Fetching upstream changes from https://xxx.yyyy.de/scm/proj/repo.git
06:01:35   > git --version # timeout=10
06:01:35  using GIT_ASKPASS to set credentials 
06:01:35   > git fetch --tags --force --progress --prune -- https://xxx.yyyy.de/scm/proj/repo.git +refs/pull-requests/580/from:refs/remotes/origin/PR-580 # timeout=10
06:01:35  ERROR: Error fetching remote repo 'origin'
06:01:35  hudson.plugins.git.GitException: Failed to fetch from https://xxx.yyyy.de/scm/proj/repo.git
06:01:35  	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:909)
06:01:35  	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1131)
06:01:35  	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1167)
06:01:35  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
06:01:35  	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:155)
06:01:35  	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:142)
06:01:35  	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:299)
06:01:35  	at hudson.model.ResourceController.execute(ResourceController.java:97)
06:01:35  	at hudson.model.Executor.run(Executor.java:427)
06:01:35  Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --force --progress --prune -- https://xxx.yyyy.de/scm/proj/repo.git +refs/pull-requests/580/from:refs/remotes/origin/PR-580" returned status code 128:
06:01:35  stdout: 
06:01:35  stderr: fatal: Couldn't find remote ref refs/pull-requests/580/from
06:01:35  
06:01:35  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2430)
06:01:35  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2044)
06:01:35  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:81)
06:01:35  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:569)
06:01:35  	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:907)
06:01:35  	... 8 more
06:01:35  ERROR: Error fetching remote repo 'origin'
06:01:35  [Bitbucket] Notifying pull request build result
06:01:36  [Bitbucket] Build result notified
06:01:36  ERROR: Maximum checkout retry attempts reached, aborting
06:01:36  Finished: FAILURE
```

https://community.atlassian.com/t5/Bitbucket-questions/Bitbucket-Server-7-0-PR-fetch-from-not-working/qaq-p/1320053

### PR DESCRIPTION
**Pull request by viceice**
This pr removes the usage of not and no longer supported bitbucket server git api.

fixes #287
fixes #302

### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Comment by wwuck** [comment]
Can we get a new release with this merged @Jetersen ?

**Comment by viceice** [comment]
Works for me, file needs to be renamed to hpi. 💪 

[cloudbees-bitbucket-branch-source.zip](https://github.com/jenkinsci/bitbucket-branch-source-plugin/files/4347566/cloudbees-bitbucket-branch-source.zip)

**Comment by Jetersen** [comment]
@viceice please do not upload files, use the once coming from the Jenkins CI

**Comment by viceice** [comment]
ok, sorry and thanks for infomation

**Comment by f-cramer** [comment]
I guess `com.cloudbees.jenkins.plugins.bitbucket.filesystem.BitbucketSCMFileSystem` should be changed with this PR as well, shouldn't it? In lines 179 and 181 are some more instances of ref/pull-requests ...

**Comment by viceice** [comment]
ok, I'll look at it

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java [hunk 1]
```diff
@@ -176,9 +176,10 @@ public SCMFileSystem build(@NonNull SCMSource source, @NonNull SCMHead head, @Ch
                         return null;
                     }
                 } else if (pr.getCheckoutStrategy() == ChangeRequestCheckoutStrategy.HEAD) {
-                    ref = "pull-requests/" + pr.getId() + "/from";
+                    ref = "heads/" + pr.getBranchName();
                 } else if (pr.getCheckoutStrategy() == ChangeRequestCheckoutStrategy.MERGE) {
-                    ref = "pull-requests/" + pr.getId() + "/merge";
+                    // No longer supported
+                    ref = null;
```
Comment (Jetersen) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java]: This makes me really sad, the one reason why Bitbucket does not make sense for any CI but their own.

Comment (viceice) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java]: Is there any other possibillity to let jenkins do the merge?

Comment (viceice) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java]: If i look at the code, jenkins is merging the pr into the target before build. So we only loose the lightweight checkout for merge?

Comment (Jetersen) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java]: Jenkins does the merge but it does so on master by cloning the entire repo.
The reason for lightweight checkout is that it prevents the Jenkins master from cloning the entire repo.

**Comment by viceice** [comment]
I've not found a possible api for checking bitbucket server version. Or there is no official api yet. 😞

**Comment by Jetersen** [comment]
Perhaps located in the header response?

**Comment by viceice** [comment]
nope

**Comment by Jetersen** [comment]
Again Bitbucket server is a mess.

**Comment by viceice** [comment]
ok, there is a possibillity to get the version [/rest/api/1.0/application-properties](https://docs.atlassian.com/bitbucket-server/rest/7.0.1/bitbucket-rest.html#idp85)

**Comment by Jetersen** [comment]
the field could be transient on bitbucket server config

**Comment by viceice** [comment]
Should I implement a bitbucket version based switch? The property is also found in anciend server version [5.16.0](https://docs.atlassian.com/bitbucket-server/rest/5.16.0/bitbucket-rest.html#idm8296895104)

**Comment by Jetersen** [comment]
So far it is only v7 which has the issue newly introduced issue.

**Comment by viceice** [comment]
ok, so I've checkd it again. The `refs/pull-requests/...` are no longer added since bitbucket server v7.

So `BitbucketSCMSource` can be changed as is, without version change.

The `build` function in `BitbucketSCMFileSystem.java` needs a bitbucket version check for `pr.getCheckoutStrategy() == ChangeRequestCheckoutStrategy.MERGE` branch to support lightweight checkout on bitbucket server version below v7.

Right?

**Comment by Jetersen** [comment]
Yup @viceice that would be much appreciated. My suggestion is to store the version once it is fetched on the bitbucket server config object.

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java [hunk 2]
```diff
@@ -176,8 +176,9 @@ public SCMFileSystem build(@NonNull SCMSource source, @NonNull SCMHead head, @Ch
                         return null;
                     }
                 } else if (pr.getCheckoutStrategy() == ChangeRequestCheckoutStrategy.HEAD) {
-                    ref = "pull-requests/" + pr.getId() + "/from";
+                    ref = "heads/" + pr.getBranchName();
                 } else if (pr.getCheckoutStrategy() == ChangeRequestCheckoutStrategy.MERGE) {
+                    // No longer supported since bitbucket server v7, falls back to heavycheckout
                     ref = "pull-requests/" + pr.getId() + "/merge";
                 }
```
Comment (viceice) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java]: @Jetersen What do you think? This supportes older bitbucket and falls back to heavy checkout on bitbucket v7 and later

Comment (Jetersen) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java]: Yup seems fine with me, properly simpler fix 😅

Comment (jftsunami) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java]: Older versions of BitBucket, while they had the pull-request refs, are not accurate. PRs get confused in our environment, and we're running 6.7.2.

Comment (viceice) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java]: So the pr refs are not updated at 6.7.2 too?

Comment (jftsunami) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java]: Not without performing a 'null' operation on the UI, such as editing and saving the PR without making any changes.

Comment (Jetersen) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java]: or using the bitbucket webhook plugin that was actually doing this work for you.

https://marketplace.atlassian.com/apps/1215474/post-webhooks-for-bitbucket?hosting=server&tab=overview

Comment (jftsunami) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java]: I'd recommend getting rid of the use of "refs/pull-requests" globally, as it was never a supported API by BitBucket, and only worked by accident or as a side effect, apparently.

Comment (Jetersen) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java]: it has been working great for others so I have to disagree.

Comment (jftsunami) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java]: Alright, but it did stop working before v7.  Not sure when.

Comment (jftsunami) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java]: Would exposing a configuration option be a compromise?

Comment (viceice) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java]: this condition only allows jenkins to do a lightweight checkout on master to fetch the jenkins file. When doing a full checkout on worker it would always fetch the correct commits with this pr.

So there is only a small window when jenkins fetches an out of date jenkinsfile. So this can only happen, if you push changes to an existing pr, which updates the jenkinsfile

Comment (jftsunami) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java]: Oh, my mistake then.

**Comment by viceice** [comment]
@Jetersen I have a idea to get this working on never bitbucket.

https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java#L1111-L1135

We can use the [diff](https://docs.atlassian.com/bitbucket-server/rest/7.0.1/bitbucket-rest.html#idp319) api to check for Jenkinsfile changes.

If `file.getRef().startsWith('refs/pull-request')` and jenkinsfile not changed, simply return target file.

**Comment by maxime-michel** [comment]
Hey, thanks for the work being done here. Our CI workflow is broken after the upgrade to BB 7.0.1 and we're glad to see this conversation started. As we got told [here](https://jira.atlassian.com/browse/BSERV-12198?focusedCommentId=2373717&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2373717), `pull-requests/*/from` refs aren't updated automatically anymore.

Out of despair, we tried to run the release candidate posted above. It wasn't able to fetch the pull request at `refs/heads/<PR_BRANCH_NAME>`, so we had to rollback. 2.7.0 at least allowed us to manually click the Diff tab in Bitbucket, which would work around the issue. I just thought I'd share that before a release goes out.

**Comment by viceice** [comment]
@maxime-michel Can you check if the `pull-requests/*/from` are updated after you use the diff api?

**Comment by viceice** [comment]
Ok, tested it myself, even after viewing the pr diff the `pull-requests/*/merge` is missing

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java [hunk 3]
```diff
@@ -104,8 +104,9 @@ public BitbucketGitSCMBuilder(@NonNull BitbucketSCMSource scmSource, @NonNull SC
                 String branchName = ((PullRequestSCMHead) head).getBranchName();
                 withRefSpec("+refs/heads/" + branchName + ":refs/remotes/@{remote}/" + head.getName());
             } else {
-                String pullId = ((PullRequestSCMHead) head).getId();
-                withRefSpec("+refs/pull-requests/" + pullId + "/from:refs/remotes/@{remote}/" + head.getName());
+                // https://community.atlassian.com/t5/Bitbucket-questions/Difference-of-refs-pull-requests-lt-ID-gt-merge-and-refs-pull/qaq-p/772142
+                String branchName = ((PullRequestSCMHead) head).getBranchName();
+                withRefSpec("+refs/heads/" + branchName + ":refs/remotes/@{remote}/" + branchName);
```
Comment (mkgl) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java]: Not sure how this is supposed to handle PRs where source branch is in a fork?
Probably fine to do a branch lookup first, but maintain the `refs/pull-requests/x/from` as a fallback?

Comment (viceice) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java]: shouldn't the `@{remote}` be the fork? 🤔

Comment (mkgl) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java]: `@{remote}` is only used in the "receiving" part of the refspec, after the colon, which just indicates how it's gonna store that ref "locally"; that's irrelevant with where it's supposed to find the source branch. Also if we were on the fork already, we wouldn't have to use those pull-requests refs in the first place. :)

Besides navigating through, as `#withRefSpec` indicates, `@{remote}` is supposed to be processed for substitution by `#remote()` before use, which is only ever gonna return a fixed remote for the current scm source, as far as I can tell.

**Comment by chq81** [comment]
@viceice Hi there. Any progess or ideas when this can be fixed. My company updated to Bitbucket v7 without giving prior notice and now all my build pipeline/workflow is broken due to the missing PR functionality.

**Comment by Jetersen** [comment]
Again I point the blame at Atlassian for breaking things.

I wonder how their bitbucket server plugin handles these refs.

**Comment by chq81** [comment]
Thanks @Jetersen. I didn't mean to imply that someone needs to fix this plugin, and I totally understand that when Atlassian changes the way of how they handle PRs, it is their fault. It just seemed that you guys are working on a solution, therefore I thought I'll ask.

**Comment by Jetersen** [comment]
No worries @chq81 :)

Checked out the Atlassian Bitbucket server plguin and they do not even offer support for these features 🤷‍♂ I still do not understand their need to create a separate plugin.

**Comment by maxime-michel** [comment]
My understanding at this point is that you'd use the Atlassian plugin to connect Jenkins and Bitbucket together (with the automatically created webhook), but that for PRs you would use: https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java (hunk 3 above)
Comment (viceice) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java]: I havn't tested with forks, because we don't use them. Maybe i can try it.

**Comment by viceice** [comment]
> @viceice Hi there. Any progess or ideas when this can be fixed. My company updated to Bitbucket v7 without giving prior notice and now all my build pipeline/workflow is broken due to the missing PR functionality.

I'm using this pr build in production, which works so far.

**Comment by chq81** [comment]
@viceice Thanks for the hint. I installed it and it works so far. Would still be nice so see it as an official release, but I guess there are still other problems to be solved before this can be merged... In addition to Atlassian either rebuilding their original functionality or adding PRs into their own plugin.

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java (hunk 2 above)
Comment (jansohn) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java:183]: I think this comment (https://jira.atlassian.com/browse/BSERV-12284?focusedCommentId=2389584&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2389584) is a quite interesting read on the topic.
Taking this into account I would also get rid of that merge ref as it does not seem to come back and it can be outdated on earlier Bitbucket versions if people don't use special Bitbucket plugins that trigger the update of the refs, e.g. when using only the native web-hooks.
I don't know this source code well enough but we might want to add that REST API call (rest/api/1.0/projects/KEY/repos/slug/pull-requests/N/changes?limit=1) to make sure the from ref is properly created/updated if we still want to use it. This would allow users to stick with the native web-hooks solution without any additional plugins.
Thoughts?

**Comment by jetersen** [comment]
Could someone test #302 with Can Merge enabled?

**Comment by maxime-michel** [comment]
Yes, let me do that. I'll report later today.

**Comment by maxime-michel** [comment]
Works for our scenario! Without the change:

1. PR is created from branch of fork against canonical's master
2. canonical's Jenkins job scan is triggered, but Jenkinsfile not found for PR
3. temporary workaround of clicking the 'Diff' tab for the PR in Bitbucket
4. manual repository scan, PR created

With this change:

1. 'Call can merge' enabled
2. PR is created from branch of fork against canonical's master
3. canonical's Jenkins job scan is triggered, Jenkinsfile found for PR
4. PR is built successfully, despite the following warnings:

```    ERROR: Could not do lightweight checkout, falling back to heavyweight
    java.io.FileNotFoundException: URL: /rest/api/1.0/projects/modules/repos/log-tools/browse/Jenkinsfile?at=pull-requests%2F33%2Fmerge&start=0&limit=500
            at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:831)
            at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getFileContent(BitbucketServerAPIClient.java:1123)
            at com.cloudbees.jenkins.plugins.bitbucket.filesystem.BitbucketSCMFile.content(BitbucketSCMFile.java:98)
            at jenkins.scm.api.SCMFile.contentAsString(SCMFile.java:335)
            at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:107)
            at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
            at hudson.model.ResourceController.execute(ResourceController.java:97)
            at hudson.model.Executor.run(Executor.java:428)
```

``` > git checkout -f a79164d0a991257c7080fa7f7b722a127d696a68 # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
…
 > git merge 7ab7a6482e437e87d7416f180134cbccd7a41c7e # timeout=10
 > git rev-parse HEAD^{commit} # timeout=10
Merge succeeded, producing a79164d0a991257c7080fa7f7b722a127d696a68
Checking out Revision a79164d0a991257c7080fa7f7b722a127d696a68 (PR-33)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f a79164d0a991257c7080fa7f7b722a127d696a68 # timeout=10
Commit message: "test-pr-2"
…
fatal: bad object a79164d0a991257c7080fa7f7b722a127d696a68
```

**Comment by Rooomchik** [comment]
Hello Everyone. I'm a newbie in such a process so sorry for something is wrong.

Our company has upgraded the Bitbucket to 7 version and we are facing the same issue.

Can you please advise if there are HL timelines fix that will be released with a newer version of the plugin?

**Comment by mlasevich** [comment]
For what its worth, I back-ported these changes against [2.5.0](https://github.com/mlasevich/bitbucket-branch-source-plugin/tree/feature/2.5.0-with-bb7) (some of us are stuck on older version of plugin thanks to CloudBees) and getting the same results as above - the API error is still there but it seems to work.

**Comment by asafp-nice** [comment]
Hi, we've also tested this PR and it indeed appears to fix the issue for us. We're using Bitbucket server 7.0.3.

Any plans on merging this to Master?

**Comment by jetersen** [comment]
As many have mentioned there is still the issue of lightweight checkout with the `FileNotFoundException` which would be great if it could get fixed.

As I do not use Bitbucket I have no way to figure out the solution.

Would prefer if the community could find a solution. I'll be happy to review and merge any PR that solves the issue.

Please see #288

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java (hunk 3 above)
Comment (JeroennC) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java:109]: We've just tested plugin version `2.7.1-rc629.f242e60a14b` with our setup which uses forks, and indeed it fails at this step as the branches can not be found on the origin

**Comment by jetersen** [comment]
https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/294#discussion_r420672772
With this comment we definitely need a better approach.

**Comment by viceice** [comment]
I think heavyweight checkout (bitbucket > v7) is required for testing merged pr's when Jenkinsfile changed. Otherwise we could fallback to the target Jenkinsfile.

The merge commit will never come back to bitbucket, so we need a possibility to get files from source branch, especially if it is from a fork.

**Comment by jetersen** [comment]
I think we should fallback to target Jenkinsfile, unless perhaps otherwise configured to use source if configured to trust collaborator?

**Comment by viceice** [comment]
@jetersen Any idea why i get this error locally?
image

**Comment by jetersen** [comment]
@viceice you need to use java 8 to build.

**Comment by JeroennC** [comment]
@jetersen - We also face issues that new PRs are not triggered due to `'Jenkinsfile' not found` on the multibranch pipeline scan. Wondering if you can assess with your domain knowledge whether this PR also applies to this issue.

I will wait for the incremental build to be available and test this, create a new issue if it persists.

**Comment by viceice** [comment]
I've reverted most changes now and added the suggested changes api call. This will hopefully bring back the `from` ref, but does not work for `merge` ref

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java [hunk 4]
```diff
@@ -337,11 +338,16 @@ public String getRepositoryUri(@NonNull BitbucketRepositoryType type,
         }
 
         AbstractBitbucketEndpoint endpointConfig = BitbucketEndpointConfiguration.get().findEndpoint(baseURL);
-        if (endpointConfig instanceof BitbucketServerEndpoint && ((BitbucketServerEndpoint)endpointConfig).isCallCanMerge()) {
+        if (endpointConfig instanceof BitbucketServerEndpoint) {
             // This is required for Bitbucket Server to update the refs/pull-requests/* references
             // See https://community.atlassian.com/t5/Bitbucket-questions/Change-pull-request-refs-after-Commit-instead-of-after-Approval/qaq-p/194702#M6829
             for (BitbucketServerPullRequest pullRequest : pullRequests) {
```
Comment (jetersen) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java:344]: Would prefer we avoid looping over these pull requests unless either `isCallCanMerge` or `isCallChanges` is enabled

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java [hunk 5]
```diff
@@ -337,11 +338,16 @@ public String getRepositoryUri(@NonNull BitbucketRepositoryType type,
...
-                pullRequest.setCanMerge(getPullRequestCanMergeById(Integer.parseInt(pullRequest.getId())));
+                if (((BitbucketServerEndpoint) endpointConfig).isCallCanMerge()) {
+                    pullRequest.setCanMerge(getPullRequestCanMergeById(Integer.parseInt(pullRequest.getId())));
+                }
+                if (((BitbucketServerEndpoint) endpointConfig).isCallChanges()) {
+                    callPullRequestChangesById(Integer.parseInt(pullRequest.getId()));
+                }
```
Comment (jetersen) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java:350]: Better to only cast it once.
Please cast the endpoint once outside the for loop
```java
                BitbucketServerEndpoint endpoint = (BitbucketServerEndpoint) endpointConfig;
```
```suggestion
                if (endpoint.isCallCanMerge()) {
                    pullRequest.setCanMerge(getPullRequestCanMergeById(Integer.parseInt(pullRequest.getId())));
                }
                if (endpoint.isCallChanges()) {
                    callPullRequestChangesById(Integer.parseInt(pullRequest.getId()));
                }
```

**Comment by viceice** [comment]
Testing the build from [here](https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fbitbucket-branch-source-plugin/detail/PR-294/15/artifacts) in our jenkins and it seem to work (heavy checkout on merge)

Can somebody test this too? I'll do the requested suggestions now.

**Comment by viceice** [comment]
@jetersen Shouln't i remove the integer parse? As we convert them to string anyways after replacing in `UrlTemplate`

**Comment by jetersen** [comment]
For the new addition, yes.
For the canMerge an extension plugin is using them as int so that would be a breaking change.

**Comment by jetersen** [comment]
Nevermind, since both are private go for it. Feel free to remove the parsing of the ids.

```java
    private void callPullRequestChangesById(@NonNull Integer id) throws IOException {
        String url = UriTemplate
                .fromTemplate(API_PULL_REQUEST_CHANGES_PATH)
                .set("owner", getUserCentricOwner())
                .set("repo", repositoryName)
                .set("id", id).set("limit", 1)
                .expand();
        getRequest(url);
    }

    private boolean getPullRequestCanMergeById(@NonNull Integer id) throws IOException {
        String url = UriTemplate
                .fromTemplate(API_PULL_REQUEST_MERGE_PATH)
                .set("owner", getUserCentricOwner())
                .set("repo", repositoryName)
                .set("id", id)
                .expand();
        String response = getRequest(url);
        try {
            return JsonParser.toJava(response, BitbucketServerPullRequestCanMerge.class).isCanMerge();
        } catch (IOException e) {
            throw new IOException("I/O error when accessing URL: " + url, e);
        }
    }
```

**Comment by viceice** [comment]
ok, done

**Comment by JeroennC** [comment]
Tested this on our setup - with forks - and it works 👍 
Falls back to heavy weight checkout to get the Jenkinsfile correctly, also now during the multibranch pipeline scan it immediately finds the Jenkinsfile and starts a build as expected.

**Comment by jetersen** [comment]
@viceice mind updating the user docs to mention bitbucket server 7 and suggest enabling the call changes api?

**Comment by viceice** [comment]
@jetersen Can you please hint me where to put the `callChanges` stuff

**Comment by jetersen** [comment]
@viceice feel free to update the remove the current important block.
And replace it with a mention on bitbucket server 7 and link to a new section you feel free to add the section at the top.

**Comment by mattiassluis** [comment]
@jetersen I contacted @viceice but he is squeezed for time. I create the doc changes here: https://github.com/mattiassluis/bitbucket-branch-source-plugin/commit/26fbc94a411c0527f3acd4d81f3dd1b62223797c and I can either create a new PR that is the same as this one or you can maybe apply those changes to this one.

**Comment by jetersen** [comment]
Let me cherry-pick it in :)

**Comment by viceice** [comment]
@mattiassluis thanks

**Comment by mattiassluis** [comment]
> Let me cherry-pick it in :)

Thank you! What's left now to get this in an official release?

File: docs/USER_GUIDE.adoc [hunk 6]
```diff
@@ -23,6 +22,14 @@ as a multi-branch project source in two different ways:
 
  IMPORTANT: This plugin is not compatible with versions of Bitbucket Server previous to 4.0.
 
+[id=bitbucket-server-7]
+== BitBucket Server 7 compatibility
+
+_BitBucket Server 7.x_ is supported but does no longer support lightweight checkout for pull requests.
```
Comment (viceice) [inline docs/USER_GUIDE.adoc:28]:
```suggestion
_BitBucket Server 7.x_ is supported but does no longer support lightweight checkout for pull requests when merge strategy is used for build.
```

Lightweight checkout works if we don't use merge build strategy.

Comment (mattiassluis) [reply docs/USER_GUIDE.adoc:28]: Ah I said that correct on the first part but it is missing here indeed. Good catch!

**Comment by mjholtkamp** [comment]
This looks great! Good work everyone! Is there something that needs to be done before a release? I'm looking forward to having this fixed :)

**Comment by serg-bs** [comment]
1. I build plugin 2.8.1-SNAPSHOT (private-98e3c549-) 
Atlassian Bitbucket v7.3.0-m1
Jenkins ver. 2.222.3
1. Install plugin manually  in jenkins. 

1. Create multibranch job with bitbucket source and Behaviours - Discover pull requests from origin "Merging the pull request with the current target branch revision"

And still have `ERROR: Could not do lightweight checkout, falling back to heavyweight
java.io.FileNotFoundException: URL: /rest/api/1.0/projects/DI/repos/goodwork/browse/Jenkinsfile?at=pull-requests%2F1%2Fmerge&start=0&limit=500` 
look like [#287 ]reproduce. What should be wrong?

**Comment by viceice** [comment]
@serg-bs As previously disscussed, you can ignore that error and it should do heavy checkout and work with bitbucket server >=7.0

**Comment by mattiassluis** [comment]
@serg-bs as you can read in the related ticket this is a problem that cannot be solved. Starting Bitbucket 7 you can no longer perform the lightweight checkout on the merge because it simply no longer exists in Bitbucket. The jobs now luckily proceed with the heavyweight and still work.
The updated docs of this plugin (in this PR) also state this: https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/294/files#diff-8528ab6ef1a37be2a6df68940c0ad37bR7

**Comment by MichaelKorn** [comment]
I installed the plugin manually from https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fbitbucket-branch-source-plugin/detail/PR-294/20/artifacts

Now, the first run of a PR looks always good with Bitbucket v7.2.3. But no further runs (if the Branch is updated) are possible, due to the following error:
```
Branch event
ERROR: Could not do lightweight checkout, falling back to heavyweight
java.io.FileNotFoundException: URL: /rest/api/1.0/projects/DBP/repos/reclis/browse/Jenkinsfile?at=pull-requests%2F8%2Fmerge&start=0&limit=500
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:855)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getFileContent(BitbucketServerAPIClient.java:1150)
	at com.cloudbees.jenkins.plugins.bitbucket.filesystem.BitbucketSCMFile.content(BitbucketSCMFile.java:98)
	at jenkins.scm.api.SCMFile.contentAsString(SCMFile.java:335)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:107)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Checking out git https://.....com/scm/DBP/reclis.git https://.....com/scm/DBP/reclis.git into /var/jenkins_home/workspace/al-Business-Platform_reclis_PR-8@script to read Jenkinsfile
using credential d93f1c48-792f-4a65-bba4-4f75ebcb9bea
using credential d93f1c48-792f-4a65-bba4-4f75ebcb9bea
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from 2 remote Git repositories
 > git config remote.origin.url https://.....com/scm/DBP/reclis.git # timeout=10
Fetching upstream changes from https://.....com/scm/DBP/reclis.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials CD/CI User
 > git fetch --tags --progress -- https://.....com/scm/DBP/reclis.git +refs/pull-requests/8/from:refs/remotes/origin/PR-8 # timeout=10
 > git config remote.upstream.url https://.....com/scm/DBP/reclis.git # timeout=10
Fetching upstream changes from https://......com/scm/DBP/reclis.git
using GIT_ASKPASS to set credentials CD/CI User
 > git fetch --tags --progress -- https://......com/scm/DBP/reclis.git +refs/heads/stage:refs/remotes/upstream/stage # timeout=10
Merging remotes/upstream/stage commit e5c90868f06713caa25fa65e12bb834f80da4a73 into PR head commit d1b96a1867121d6f0e9f28fb1f017738a17b6897
 > git config core.sparsecheckout # timeout=10
 > git checkout -f d1b96a1867121d6f0e9f28fb1f017738a17b6897 # timeout=10
ERROR: Checkout failed
hudson.plugins.git.GitException: Command "git checkout -f d1b96a1867121d6f0e9f28fb1f017738a17b6897" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: d1b96a1867121d6f0e9f28fb1f017738a17b6897

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2430)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$1100(CliGitAPIImpl.java:81)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2743)
Caused: hudson.plugins.git.GitException: Could not checkout d1b96a1867121d6f0e9f28fb1f017738a17b6897
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2767)
	at jenkins.plugins.git.MergeWithGitSCMExtension.checkout(MergeWithGitSCMExtension.java:144)
	at jenkins.plugins.git.MergeWithGitSCMExtension.decorateRevisionToBuild(MergeWithGitSCMExtension.java:110)
	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1063)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1168)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:125)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:155)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:142)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
[Bitbucket] Notifying pull request build result
[Bitbucket] Build result notified
ERROR: Maximum checkout retry attempts reached, aborting
Finished: FAILURE
```
Ich suppose the cached git repository should be reset. As workaround a delete jenkins_home/workspace/[PR-FOLDER] on the jenkins master and one additional run is possible. Before the next run I have to delete it again.

**Comment by viceice** [comment]
@MichaelKorn did you checked the `Call Changes api` checkbox ?

**Comment by MichaelKorn** [comment]
Unfortunately I missed the note regarding the checkbox, sorry!
Now it's working. THX @viceice

**Comment by wejrox** [comment]
Any news on this PR being merged? Or when a new release will be if that's what we're waiting for?

**Comment by jetersen** [comment]
If someone else wants it released I'd suggest asking for maintainership.
[Please read about adopting a plugin](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/)
Also see https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/288

I for one cannot comfortably release this PR without working lightweight checkout for existing users.

**Comment by joppa27** [comment]
@jetersen I just want to take time to thank you & the rest of your team for all the work that you have done on this plugin.  It has made my life as a Bitbucket Server customer so much easier, and given me the flexibility to adopt different CI workflows.  I can only imagine how frustrating it is for you all that this plugin has essentially been broken by changes you had no control over.

I don't fully understand why Atlassian chose to make their own plugin instead of refactoring this one. The new plugin they made currently lacks a lot of the functionality I've come to depend on that you and your team made. I don't think Atlassian fully thought this through, and that decision is going to result in a lot of work for their customers. 

You & your team should not be responsible for Atlassians's decisions & I fully support you putting this plugin up for adoption. In my opinion that's the only logical choice.  If there's a place where I can donate some money or buy your and your team some beers please let me know.

Again Thank you all for all the work you have done and continue to do!! :)

**Comment by joppa27** [comment]
A well deserved Thank you goes out to Cloudbees too!

As much as I need/want the fix to be merged, stepping up to be a maintainer when the direction Atlassian wants to go in isn't clear doesn't make sense. The least I can do is sponsor you, and hope a resolution happens soon whatever that resolution happens to be.

**Comment by faizan2131993** [comment]
Thanks, Cloudbees, and everyone who has worked on the above issue to be gets fixed.

I see the changes have been approved. Do you have any plans to release a new version with this fix to the Jenkins market? This fix is really great and it may help many of us with this fix.

I appreciate the kind works here. Thank you.

**Comment by jglick** [comment]
Have been running https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/294/commits/98e3c549af772f1e40959711bc8fac5ed9b50561 on some play projects in BB Server 7. Works if you check the new **Call changes API** checkbox AFAICT.

**Comment by kshultzCB** [comment]
Is anyone aware of a reason why the setting this checkbox enables shouldn't be turned on all the time?

I have not done a full compatibility matrix of tests by any stretch (different combinations of settings, Cloud versus Server, forks, various branches, etc), but I did try this PR against Bitbucket 5 running in a docker container locally. The checkbox had no apparent ill effects on this basic test:

```
Branch indexing
Obtained Jenkinsfile from 35db29eccaafe28acac65a19b0ffe5d5c23cfe1d+62b7ff7d2c619f5d7abf90c6317b610668d07084
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in /Users/kshultz/GitHub/bitbucket-branch-source-plugin/work/workspace/checked5_PR-2
[Pipeline] {
[Pipeline] stage
[Pipeline] { (A Stage)
[Pipeline] echo
Basic Jenkinsfile
[Pipeline] sh
+ whoami
kshultz
[Pipeline] echo
Goodbye
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
[Bitbucket] Notifying pull request build result
[Bitbucket] Build result notified
Finished: SUCCESS
```
