### PR TITLE
Fix CHANGE_AUTHOR and CHANGE_AUTHOR_DISPLAY_NAME

### LINKED ISSUE #195: CHANGE_AUTHOR variable not set
### Your checklist for this issue

- [x] Jenkins version **2.150.2**

- [x]  Plugin version **2.4.4**

- [x]  Bitbucket cloud

### Description

Having a problem where our builds are failing because we are trying to access the variable `${CHANGE_AUTHOR}` and it is not set - this appears to have changed since 2.4, but I can't confirm for sure.

As an example, in our Jenkinsfile:

```groovy
pipeline {
...
  stages {
  ...
    stage('Run detection scripts') {
      steps {
        script {
          AUTHOR_ID=sh([script: "./scripts/ci/author_id_script.sh ${CHANGE_AUTHOR} | tail -n1", returnStdout: true]).trim()
          currentBuild.displayName = "${CHANGE_TITLE}"
          currentBuild.description = "PR-${CHANGE_ID}"
        }
      }
    }
```

This first part of the script fails because `${CHANGE_AUTHOR}` is no longer defined.

### PR DESCRIPTION
**Pull request by jglick**
Fixes #195, which is not a plugin regression, but a [cloud API regression](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/) to satisfy GDPR. There is apparently no way to set `CHANGE_AUTHOR` to the previous value. (`CHANGE_FORK`, or its first component if `/`-separated, is probably the same thing, though this is not necessarily the _author_.) Nor is `CHANGE_AUTHOR_EMAIL` possible.

Also, for Server, the display name was mistakenly being bound to the variable intended for the (code) username.

Example variables with BB Cloud, before:

```
(no variables starting with CHANGE_AUTHOR)
```

after:

```
CHANGE_AUTHOR=123456:some-long-uuid
CHANGE_AUTHOR_DISPLAY_NAME=Jesse Glick
```

With BB Server 7, before:

```
CHANGE_AUTHOR=Test User
CHANGE_AUTHOR_EMAIL=testuser@nowhere.net
```

and after:

```
CHANGE_AUTHOR=test-user
CHANGE_AUTHOR_DISPLAY_NAME=Test User
CHANGE_AUTHOR_EMAIL=testuser@nowhere.net
```

### CODE REVIEW

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEvent.java [hunk 1]
```diff
@@ -73,7 +73,7 @@ private void reconstructMissingData() {
                     if (this.pullRequest.getSource().getRepository().getOwnerName().equals(this.pullRequest.getAuthorLogin())) {
```
Comment (jglick) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEvent.java:73]: Whatever this code was doing, it can no longer work. For example, `.source.repository.full_name` might be `jglick/somerepo`, but the `jglick` part is no longer accessible from the API.

Comment (jglick) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEvent.java:73]: Investigating failures in `BitbucketCloudPullRequestEventTest`. There seems to be a real problem here—not a regression from my patch, but brought to light by the updates to mock API responses.

Comment (jglick) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEvent.java:73]: (Manually triggered scans and pull request builds seem to work fine as is, but IIUC this code is dealing specifically with webhooks.)

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/pullrequest/BitbucketPullRequestValue.java [hunk 2]
```diff
@@ -155,27 +151,15 @@ public void setHref(String href) {
...
-        public void setUsername(String username) {
-            this.username = username;
-        }
 
         public String getIdentifier() {
             return identifier;
         }
 
-        public void setIndentifier(String identifier) {
+        public void setIdentifier(String identifier) {
```
Comment (jglick) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/pullrequest/BitbucketPullRequestValue.java:162]: [no known external uses](https://github.com/search?ref=simplesearch&type=Code&q=user%3Ajenkinsci+BitbucketPullRequestValue)

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEvent.java (hunk 1 above)
Comment (jglick) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEvent.java:73]: #37 FTR

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEvent.java [hunk 3]
```diff
@@ -70,15 +70,15 @@ private void reconstructMissingData() {
...
-                        owner.setUsername(this.pullRequest.getAuthorLogin());
-                        owner.setDisplayName(this.pullRequest.getAuthorDisplayName());
+                        owner.setUsername(this.pullRequest.getSource().getRepository().getOwnerName());
+                        owner.setDisplayName(this.pullRequest.getAuthorLogin());
                         if (repository.isPrivate()) {
                             this.pullRequest.getSource().getRepository().setPrivate(repository.isPrivate());
                         }
                         this.pullRequest.getSource().getRepository().setOwner(owner);
-                    } else if (this.pullRequest.getSource().getRepository().getOwnerName().equals(repository.getOwnerName())) {
+                    } else { // origin branch
```
Comment (jglick) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEvent.java:81]: Possibly fixes a bug with the handling of webhooks for forked PRs in BB Cloud, though I am not sure how to test that outside a mock context (discovered due to unit test failures): I cannot find any non-test usages of `BitbucketRepository.getOwner` except for code in this `reconstructMissingData` method which _sets_ an `owner` field. Perhaps @stephenc can clarify if he still remembers anything about it (but this was over three years ago).
