### PR TITLE
Fix Automatic Webhook Creation for BitBucket 5.x [Fixes 352]

### LINKED ISSUE #352: WebHook registration fails with v. 2.9.1 of plugin towards BitBucket Server 5.16.11
### Your checklist for this issue

- [x] Jenkins version: CloudBees Jenkins Distribution 2.235.4.1

- [x] Plugin version: 2.9.1

- [x] Bitbucket cloud: NA

- [x] Bitbucket server and version: 5.16.11

### Description

We are using CloudBees Jenkins Distribution (v 2.235.4.1) which enforces version 2.9.1 of this plugin. Towards BitBucket Server version 5.16.11, the WebHook registration fails with HTTP Status 400 (Bad Request):

```
2020-08-17 11:27:03.283+0000 [id=350]	WARNING	c.c.j.p.b.h.WebhookAutoRegisterListener$1#doRun: Could not register hooks for XXX
--
  | com.cloudbees.jenkins.plugins.bitbucket.api.BitbucketRequestException: HTTP request error. Status: 400: .
  | HttpResponseProxy{HTTP/1.1 400  XXXX
  | at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.doRequest(BitbucketServerAPIClient.java:1069)
  | at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.putRequest(BitbucketServerAPIClient.java:1080)
  | at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.updateCommitWebHook(BitbucketServerAPIClient.java:651)
  | at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener.registerHook(WebhookAutoRegisterListener.java:181)
  | at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener.registerHooks(WebhookAutoRegisterListener.java:133)
  | at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener.access$000(WebhookAutoRegisterListener.java:56)
  | at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener$1.doRun(WebhookAutoRegisterListener.java:102)
  | at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:91)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)

```

### PR DESCRIPTION
**Pull request by ssc327**
Reorganize hook events for different BitBucket versions and introduce settings for versions 7, 6, 5.10 and earlier than 5.10

Version 2.80 accidentally added some default hook events that are only available on version 5.10+

Tested against BB v5.4

Fixes #352 

### Your checklist for this pull request

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [X] Link to relevant pull requests, esp. upstream and downstream changes
- [X] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/HookEventType.java [hunk 1]
```diff
@@ -100,14 +100,14 @@
...
-     * @since Bitbucket Server 5.4
+     * @see <a href="https://confluence.atlassian.com/bitbucketserver0510/event-payload-951390742.html">Eventpayload-Modified</a>
+     * @since Bitbucket Server 5.10
      */
     SERVER_PULL_REQUEST_MODIFIED("pr:modified", NativeServerPullRequestHookProcessor.class),
 
     /**
-     * @see <a href="https://confluence.atlassian.com/bitbucketserver054/event-payload-939508609.html#Eventpayload-ReviewersUpdated">Eventpayload-Modified</a>
-     * @since Bitbucket Server 6.8
+     * @see <a href="https://confluence.atlassian.com/bitbucketserver0510/event-payload-951390742.html">Eventpayload-Modified</a>
```
Comment (bitwiseman) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/HookEventType.java:109]:
```suggestion
     * @see <a href="https://confluence.atlassian.com/bitbucketserver0510/event-payload-951390742.html#Eventpayload-ReviewersUpdated">Eventpayload-Modified</a>
```

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/HookEventType.java [hunk 2]
```diff
@@ -100,14 +100,14 @@
     SERVER_PULL_REQUEST_APPROVED("pr:reviewer:approved", NativeServerPullRequestHookProcessor.class),
 
     /**
-     * @see <a href="https://confluence.atlassian.com/bitbucketserver068/event-payload-981145451.html#Eventpayload-Modified">Eventpayload-Modified</a>
-     * @since Bitbucket Server 5.4
+     * @see <a href="https://confluence.atlassian.com/bitbucketserver0510/event-payload-951390742.html">Eventpayload-Modified</a>
```
Comment (bitwiseman) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/HookEventType.java:103]:
```suggestion
     * @see <a href="https://confluence.atlassian.com/bitbucketserver0510/event-payload-951390742.html#Eventpayload-Modified.1">Eventpayload: Pull Request - Modified</a>
```

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/BitbucketServerVersion.java [hunk 3]
```diff
@@ -27,7 +27,9 @@
 
 public enum BitbucketServerVersion implements ModelObject {
     VERSION_7("Bitbucket v7.x (and later)"),
-    VERSION_6("Bitbucket v6.x (and earlier)");
+    VERSION_6("Bitbucket v6.x (and later)"),
+    VERSION_5_10("Bitbucket v5.10 (and later)"),
```
Comment (bitwiseman) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/BitbucketServerVersion.java:31]:
```suggestion
    VERSION_5_10("Bitbucket v5.10 to v5.16"),
```

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java [hunk 4]
```diff
@@ -203,9 +208,21 @@ public BitbucketWebHook getHook(BitbucketSCMSource owner) {
...
+            case VERSION_5_9:
+				return NATIVE_SERVER_EVENTS_v5_9;
+            case VERSION_5_10:
+				return NATIVE_SERVER_EVENTS_v5_10;
+            case VERSION_6:
+				// plugin version 2.9.1 introduced VERSION_6 setting for BitBucket but it actually applies
+				// to Version 5.10+. In order to preserve backwards compatibility, rather than remove
+				// VERSION_6, it will use the same list as 5.10 until such time a need arises for it to have its
+				// own list
+				return NATIVE_SERVER_EVENTS_v5_10;
```
Comment (bitwiseman) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java:221]:
```suggestion
            case VERSION_5_10:
				// plugin version 2.9.1 introduced VERSION_6 setting for BitBucket but it actually applies
				// to Version 5.10+ for events.
				return NATIVE_SERVER_EVENTS_v6;
            case VERSION_6:
				return NATIVE_SERVER_EVENTS_v6;
```

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java [hunk 5]
```diff
@@ -67,16 +66,22 @@
...
+            // only on v5.10 and above
             HookEventType.SERVER_PULL_REQUEST_MODIFIED.getKey(),
             HookEventType.SERVER_PULL_REQUEST_REVIEWER_UPDATED.getKey(),
             // only on v7.x and above
             HookEventType.SERVER_PULL_REQUEST_FROM_REF_UPDATED.getKey()
     ));
 
     /**
-     * The list of events available in Bitbucket Server v6.x.
+     * The list of events available in Bitbucket Server v5.10+.
```
Comment (bitwiseman) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java:77]:
```suggestion
     * The list of events available in Bitbucket Server v6.x.  Applies to v5.10+. 
```

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java [hunk 6]
```diff
@@ -67,16 +66,22 @@
...
      */
-    private static final List<String> NATIVE_SERVER_EVENTS_v6 = Collections.unmodifiableList(NATIVE_SERVER_EVENTS_v7.subList(0, 6));
+    private static final List<String> NATIVE_SERVER_EVENTS_v5_10 = Collections.unmodifiableList(NATIVE_SERVER_EVENTS_v7.subList(0, 7));
```
Comment (bitwiseman) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java:79]:
```suggestion
    private static final List<String> NATIVE_SERVER_EVENTS_v6 = Collections.unmodifiableList(NATIVE_SERVER_EVENTS_v7.subList(0, 7));
```

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/BitbucketServerVersion.java (hunk 3 above)
Comment (bitwiseman) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/BitbucketServerVersion.java:31]:
```suggestion
    VERSION_6("Bitbucket v6.x"),
    VERSION_5_10("Bitbucket v5.10 to v5.16"),
```
```

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/BitbucketServerVersion.java [hunk 7]
```diff
@@ -27,7 +27,9 @@
 
 public enum BitbucketServerVersion implements ModelObject {
     VERSION_7("Bitbucket v7.x (and later)"),
-    VERSION_6("Bitbucket v6.x (and earlier)");
+    VERSION_6("Bitbucket v6.x"),
+    VERSION_5_10("Bitbucket v5.10 to v5.16"),
+    VERSION_5_9("Bitbucket v5.9 (and earlier)");
```
Comment (bitwiseman) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/BitbucketServerVersion.java:32]:
```suggestion
    VERSION_5("Bitbucket v5.9 (and earlier)");
```

File: src/test/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfigurationTest.java [hunk 8]
```diff
@@ -741,5 +741,25 @@ public void should_support_configuration_as_code() throws Exception {
...
+        
+        serverEndpoint = (BitbucketServerEndpoint) instance.getEndpoints().get(10);
+        assertThat(serverEndpoint.getDisplayName(), is("Example Inc"));
+        assertThat(serverEndpoint.getServerUrl(), is("http://bitbucket.example.com:8090"));
+        assertThat(serverEndpoint.isManageHooks(), is(false));
+        assertThat(serverEndpoint.getCredentialsId(), is(nullValue()));
+        assertThat(serverEndpoint.isCallCanMerge(), is(false));
+        assertThat(serverEndpoint.isCallChanges(), is(true));
+        assertThat(serverEndpoint.getWebhookImplementation(), is(BitbucketServerWebhookImplementation.PLUGIN));
+        assertThat(serverEndpoint.getServerVersion(), is(BitbucketServerVersion.VERSION_5_9));
```
Comment (bitwiseman) [inline src/test/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfigurationTest.java:762]:
```suggestion
        assertThat(serverEndpoint.getServerVersion(), is(BitbucketServerVersion.VERSION_5));
```

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java [hunk 9]
```diff
@@ -203,9 +208,21 @@ public BitbucketWebHook getHook(BitbucketSCMSource owner) {
     private static List<String> getNativeServerEvents(String serverUrl) {
         AbstractBitbucketEndpoint endpoint = BitbucketEndpointConfiguration.get().findEndpoint(serverUrl);
         if (endpoint instanceof BitbucketServerEndpoint) {
-            if (((BitbucketServerEndpoint)endpoint).getServerVersion().equals(BitbucketServerVersion.VERSION_6)) {
-                return NATIVE_SERVER_EVENTS_v6;
-            }
+            switch (((BitbucketServerEndpoint) endpoint).getServerVersion()) {
+            case VERSION_5_9:
```
Comment (bitwiseman) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java:212]:
```suggestion
            case VERSION_5:
```

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java (hunk 6 above)
Comment (ssc327) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java:79]: Do you think this could be confusing since these also apply to v5.10?

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java [hunk 10]
```diff
@@ -67,16 +66,22 @@
...
-     * The list of events available in Bitbucket Server v6.x.
+     * The list of events available in Bitbucket Server v5.10+.
      */
-    private static final List<String> NATIVE_SERVER_EVENTS_v6 = Collections.unmodifiableList(NATIVE_SERVER_EVENTS_v7.subList(0, 6));
+    private static final List<String> NATIVE_SERVER_EVENTS_v5_10 = Collections.unmodifiableList(NATIVE_SERVER_EVENTS_v7.subList(0, 7));
+
+    /**
+     * The list of events available in Bitbucket Server v5.9-.
+     */
+    private static final List<String> NATIVE_SERVER_EVENTS_v5_9 = Collections.unmodifiableList(NATIVE_SERVER_EVENTS_v7.subList(0, 5));
```
Comment (bitwiseman) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java:84]:
```suggestion
    private static final List<String> NATIVE_SERVER_EVENTS_v5 = Collections.unmodifiableList(NATIVE_SERVER_EVENTS_v7.subList(0, 5));
```

File: src/test/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfigurationTest.java [hunk 11]
```diff
@@ -0,0 +1,81 @@
+package com.cloudbees.jenkins.plugins.bitbucket.hooks;
+
+import static org.junit.Assert.assertFalse;
```
Comment (bitwiseman) [inline src/test/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfigurationTest.java:3]: We `import static` after regular `import`.

File: src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfigurationTest/configuration-as-code.yml [hunk 12]
```diff
@@ -58,4 +58,16 @@ unclassified:
...
+        serverUrl: "http://bitbucket.example.com:8089"
+        callCanMerge: false
+        callChanges: true
+        serverVersion: VERSION_5_10
+    - bitbucketServerEndpoint:
+        displayName: "Example Inc"
+        serverUrl: "http://bitbucket.example.com:8090"
+        callCanMerge: false
+        callChanges: true
+        serverVersion: VERSION_5_9
```
Comment (bitwiseman) [inline src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfigurationTest/configuration-as-code.yml:72]:
```suggestion
        serverVersion: VERSION_5
```

File: src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfigurationTest/configuration-as-code.yml [hunk 13]
```diff
@@ -0,0 +1,33 @@
...
+        callCanMerge: false
+        callChanges: true
+        serverVersion: VERSION_5_10
+        webhookImplementation: NATIVE        
+    - bitbucketServerEndpoint:
+        displayName: "Example Inc"
+        serverUrl: "http://bitbucket.example.com:8090"
+        callCanMerge: false
+        callChanges: true
+        serverVersion: VERSION_5_9
```
Comment (bitwiseman) [inline src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfigurationTest/configuration-as-code.yml:31]:
```suggestion
        serverVersion: VERSION_5
```

**Review by bitwiseman — CHANGES_REQUESTED** [review]
Sorry about the single suggestions, I was clicking the wrong button.  

This is great work, figuring out where the cutover was. 

My suggestions are minor nits and formatting. Fix those and this looks good to merge.

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java (hunk 6 above)
Comment (bitwiseman) [reply src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java:79]: I'd rather have a change the name of the variable. I expect v6 to be supported for longer, at some point we'll want to remove support for 5.x and I would like to make that process be a matter of deleting lines that refer to 5.x (not changing variable names again.

I'd also be okay with: 
```java
    /**
     * The list of events available in Bitbucket Server v5.10 to 5.16 is the same a Bitbucket Server 6.x.        
     */
    private static final List<String> NATIVE_SERVER_EVENTS_v5_10 = NATIVE_SERVER_EVENTS_v6;
```

**Comment by ssc327** [comment]
@bitwiseman changes made, please have a look.

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java [hunk 14]
```diff
@@ -179,32 +184,47 @@ public BitbucketWebHook getHook(BitbucketSCMSource owner) {
...
-                return hook;
-            }
+        case NATIVE: {
+            NativeBitbucketServerWebhook hook = new NativeBitbucketServerWebhook();
+            hook.setActive(true);
+            hook.setEvents(getNativeServerEvents(serverUrl));
+            hook.setDescription(description);
+            hook.setUrl(getNativeServerWebhookUrl(serverUrl, rootUrl));
+            return hook;
+        }
```
Comment (bitwiseman) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java:194]:
```suggestion
            case NATIVE: {
                NativeBitbucketServerWebhook hook = new NativeBitbucketServerWebhook();
                hook.setActive(true);
                hook.setEvents(getNativeServerEvents(serverUrl));
                hook.setDescription(description);
                hook.setUrl(getNativeServerWebhookUrl(serverUrl, rootUrl));
                return hook;
            }
```

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java [hunk 15]
```diff
@@ -179,32 +184,47 @@ public BitbucketWebHook getHook(BitbucketSCMSource owner) {
...
-            }
+        case PLUGIN:
+        default: {
+            BitbucketServerWebhook hook = new BitbucketServerWebhook();
+            hook.setActive(true);
+            hook.setDescription(description);
+            hook.setUrl(rootUrl + BitbucketSCMSourcePushHookReceiver.FULL_PATH);
+            hook.setCommittersToIgnore(committersToIgnore);
+            return hook;
+        }
```
Comment (bitwiseman) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java:204]:
```suggestion
            case PLUGIN:
            default: {
                BitbucketServerWebhook hook = new BitbucketServerWebhook();
                hook.setActive(true);
                hook.setDescription(description);
                hook.setUrl(rootUrl + BitbucketSCMSourcePushHookReceiver.FULL_PATH);
                hook.setCommittersToIgnore(committersToIgnore);
                return hook;
            }
```

**Review by bitwiseman — APPROVED** [review]
