### PR TITLE
fix Job DSL by adding a DataboundSetter it can understand

### LINKED ISSUE #258: traits stopped working in 2.6.0 for job-dsl
- Jenkins version: 2.190.2
- Plugin version: 2.6.0
- Bitbucket server: 5.16.0

I used to be able to configure this via the job-dsl plugin:

```
    organizationFolder('foo') {
        displayName('Foobar')

        organizations {
          bitbucket {
            serverUrl('https://stash.foobar.com')
            repoOwner('foo')
            credentialsId('stash-token')

            traits {
              sourceWildcardFilter {
                includes('sample-project')
                excludes('')
              }
            }
          }
        }
```

this is not working anymore since version 2.6.0: 
Screenshot 2019-11-11 at 10 20 47

**Downgrading to 2.5.0 fixes the issue and brings back traits:**

Screenshot 2019-11-11 at 11 13 59

Jira ticket: https://issues.jenkins-ci.org/browse/JENKINS-60155

### PR DESCRIPTION
**Pull request by casz**
Reverts the changes made to traits in 2.6.0 release
as it prevents JobDSL from working with traits

fixes #258

### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Comment by casz** [comment]
Feel free to check https://github.com/jenkinsci/bitbucket-branch-source-plugin/compare/cloudbees-bitbucket-branch-source-2.5.0...cloudbees-bitbucket-branch-source-2.6.0 to confirm

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java [hunk 1]
```diff
@@ -225,7 +225,8 @@ public void setCredentialsId(@CheckForNull String credentialsId) {
     @DataBoundSetter
     public void setTraits(@CheckForNull List<SCMTrait<? extends SCMTrait<?>>> traits) {
```
Comment (casz) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java]: the new SCM api prevents using reduced generics on the setter, however that should be fine.

**Comment by casz** [comment]
Hmmm seems that the issue is related to something else 🤔

**Comment by casz** [comment]
Unsure why traits stopped showing up in v2.6.0

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java [hunk 2]
```diff
@@ -213,19 +213,45 @@ public String getRepoOwner() {
...
+     * Sets the behavioural traits that are applied to this navigator and any {@link BitbucketSCMSource} instances it
+     * discovers. The new traits will take affect on the next navigation through any of the
+     * {@link #visitSources(SCMSourceObserver)} overloads or {@link #visitSource(String, SCMSourceObserver)}.
+     *
+     * @param traits the new behavioural traits.
+     */
+    @SuppressWarnings({"unchecked", "rawtypes"})
     @DataBoundSetter
-    public void setTraits(@CheckForNull List<SCMTrait<? extends SCMTrait<?>>> traits) {
+    public void setTraits(@CheckForNull SCMTrait[] traits) {
```
Comment (casz) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java]: Why we need these hacks is beyond me 😱 @daspilker @rsandell

**Comment by darxriggs** [comment]
I did some research how `setTraits` was/is implemented and relevant changes.

**BitbucketSCMNavigator**
[2.6.0](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/cloudbees-bitbucket-branch-source-2.6.0/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java#L226): `public void setTraits(@CheckForNull List<SCMTrait<? extends SCMTrait<?>>> traits)`
[2.5.0](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/cloudbees-bitbucket-branch-source-2.5.0/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java#L229): `public void setTraits(@NonNull List<SCMTrait> traits)`

**BitbucketSCMSource**
[2.6.0](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/cloudbees-bitbucket-branch-source-2.6.0/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java#L345): `public void setTraits(@CheckForNull List<SCMSourceTrait> traits)`
[2.5.0](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/cloudbees-bitbucket-branch-source-2.5.0/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java#L345): `public void setTraits(@CheckForNull List<SCMSourceTrait> traits)`

I also found pr#104 which also touched this method interface to workaround a problem with generics.

Maybe you want to revert the method interface to this state to be consistent.

**Comment by casz** [comment]
I tried reverting to earlier state but that would mean I had to user older version of the scm api...

Had a look at how GitHub and GitLab bitbucket manage to continue to work.
Please have a look at their code base.

**Comment by casz** [comment]
See https://github.com/jenkinsci/github-branch-source-plugin/blob/23c8a226eef074da7b87bc4b629f6a9f75bf4766/src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java#L314-L344

**Comment by casz** [comment]
Look at the git blame @rsandell changed it 12 months ago while updating deps

**Comment by casz** [comment]
Again see https://github.com/jenkinsci/github-branch-source-plugin/pull/203 😓

**Comment by darxriggs** [comment]
Thanks. Got it.
