### PR TITLE
Bug/336 | Fall back to heavyweight checkout for bitbucket v7

### LINKED ISSUE #336: Single file retrieval from PR uses outdated Bitbucket API
### Your checklist for this issue

- [x ] Jenkins version

- [ x] Plugin version

- [ ] Bitbucket cloud

- [ x] Bitbucket server and version

### Description

Jenkins version: 2.235.3
Plugin version: 2.9.1
Bitbucket server and version: 7.4.0

When the plugin needs to retrieve a single file from a pull-request in Bitbucket server it uses the at=pull-request reference which doesn't seem to be supported post Bitbucket 7+.

Example snippet that triggers this behaviour

```
pipeline {

    agent {
        kubernetes {
            customWorkspace 'myworkspace'
            label 'mylabel'
            yamlFile 'Jenkinsfile.yml'
            defaultContainer 'java'
        }
    }

    stages {
        stage("Build") {
            steps {
	      sh "echo 'hello'"
            }
        }
    }
}
```
(line 7 with yamlFile being the culprit)

Stacktrace:
```
java.io.FileNotFoundException: URL: /rest/api/1.0/projects/test/repos/my-repro/browse/Jenkinsfile.yml?at=pull-requests%2F14%2Fmerge&start=0&limit=500
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:854)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getFileContent(BitbucketServerAPIClient.java:1149)
	at com.cloudbees.jenkins.plugins.bitbucket.filesystem.BitbucketSCMFile.content(BitbucketSCMFile.java:98)
	at jenkins.scm.api.SCMFile.contentAsString(SCMFile.java:335)
```

This is related to issue #294 where a similar issue was fixed, but this feels like a case that was left behind.

### PR DESCRIPTION
**Pull request by sams-gleb**
Fixes #336 (actually more of a workaround)

Don't return ref for API calls with BB v7 so that heavyweight checkout will happen for steps like `readTrusted`

### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

File: src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java [hunk 1]
```diff
@@ -178,8 +182,17 @@ public SCMFileSystem build(@NonNull SCMSource source, @NonNull SCMHead head, @Ch
...
+                    // We don't return `ref` when working with v7
+                    // so that pipeline steps retrieving single files fall back to heavyweight checkout properly
+                    AbstractBitbucketEndpoint endpointConfig = BitbucketEndpointConfiguration.get().findEndpoint(src.getServerUrl());
+                    final BitbucketServerEndpoint endpoint = endpointConfig instanceof BitbucketServerEndpoint ?
+                            (BitbucketServerEndpoint) endpointConfig : null;
+                    if (endpoint != null) {
+                        if(endpoint.getServerVersion() != BitbucketServerVersion.VERSION_7) {
+                            ref = "pull-requests/" + pr.getId() + "/merge";
+                        }
+                    }
```
Comment (bitwiseman) [inline src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java:195]: Looking at line 177 above it seems we should return `null` rather than a `ref = null`. 

This is where the fallback occurs, I believe. 
https://github.com/jenkinsci/scm-api-plugin/blob/767f59ed48d68e73d7d3a34a0ca85e96df874b30/src/main/java/jenkins/scm/api/SCMFileSystem.java#L197-L205 



```suggestion
                    // Bitbucket server v7 doesn't support `merge` endpoint
                    // We don't return `ref` when working with v7
                    // so that pipeline steps retrieving single files fall back to heavyweight checkout properly
                    AbstractBitbucketEndpoint endpointConfig = BitbucketEndpointConfiguration.get().findEndpoint(src.getServerUrl());
                    final BitbucketServerEndpoint endpoint = endpointConfig instanceof BitbucketServerEndpoint ?
                            (BitbucketServerEndpoint) endpointConfig : null;
                    if (endpoint != null && endpoint.getServerVersion() != BitbucketServerVersion.VERSION_7) {
                        ref = "pull-requests/" + pr.getId() + "/merge";
                    } else {
                        // returning null 
                        return null;
                    }
```

**Comment by bitwiseman** [comment]
@sams-gleb 
Have you tested this locally?  Does it check out the right ref?

**Review by dwnusbaum — APPROVED** [review]
Looks fine to me assuming it works!

**Comment by bitwiseman** [comment]
I've manually verified this.  

Before:
```
Started by user unknown or anonymous
Replayed #3
ERROR: Could not do lightweight checkout, falling back to heavyweight
java.io.FileNotFoundException: URL: /rest/api/1.0/projects/test1/repos/test-repo-1/browse/Jenkinsfile?at=pull-requests%2F2%2Fmerge&start=0&limit=500
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:856)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getFileContent(BitbucketServerAPIClient.java:1152)
	at com.cloudbees.jenkins.plugins.bitbucket.filesystem.BitbucketSCMFile.content(BitbucketSCMFile.java:98)
	at jenkins.scm.api.SCMFile.contentAsString(SCMFile.java:335)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:107)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] echo
Hello
[Pipeline] echo
Hello2
[Pipeline] readTrusted
[Pipeline] End of Pipeline
[Bitbucket] Notifying pull request build result
[Bitbucket] Build result notified
java.io.FileNotFoundException: URL: /rest/api/1.0/projects/test1/repos/test-repo-1/browse/Jenkinsfile?at=pull-requests%2F2%2Fmerge&start=0&limit=500
	at 
...
```

After: 
```
Started by user unknown or anonymous
Replayed #2
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] echo
Hello
[Pipeline] echo
Hello2
[Pipeline] readTrusted
Checking out PR-2-merge to read Jenkinsfile
using credential c0391574-e98b-464b-83ca-7ad890334c7c
using credential c0391574-e98b-464b-83ca-7ad890334c7c
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from 2 remote Git repositories
 > git config remote.origin.url http://localhost:7990/scm/test1/test-repo-1.git # timeout=10
Fetching without tags
...
Merging remotes/upstream/master commit 2d8425b4cee02b12b35d5b2b771398ac271f6c89 into PR head commit bbda1d5bc16d007c98b4d75675f133c2bc48d514
...
```

**Comment by Lakhtenkov-iv** [comment]
Hi @bitwiseman Did you test your changes on BitBucket version 6. Because I'm experiencing following:
**BitBucket version**: Atlassian Bitbucket v6.10.7
**Jenkins Master**: 2.249.1
**cloudbees-bitbucket-branch-source**: 2.9.6
**Actual behavior**: 
Falling back to heavyweight checkout without lightweight try
```
Started by user Lakhtenkov Igor
Checking out git https://*****.com/scm/~ilakhtenkov/ilakhtenkov_test.git https://******.com/scm/~ilakhtenkov/ilakhtenkov_test.git into /var/jenkins_home/workspace/multibranch_test_PR-5@script to read Jenkinsfile
The recommended git tool is: NONE
using credential ********-****-****-****-************
using credential ********-****-****-****-************
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository https://*****.com/scm/~ilakhtenkov/ilakhtenkov_test.git
 > git init /var/jenkins_home/workspace/multibranch_test_PR-5@script # timeout=10
Fetching upstream changes from https://******.com/scm/~ilakhtenkov/ilakhtenkov_test.git
 > git --version # timeout=10
 > git --version # 'git version 2.11.0'
using GIT_ASKPASS to set credentials System User
 > git fetch --no-tags --progress -- https://*****.com/scm/~ilakhtenkov/ilakhtenkov_test.git +refs/pull-requests/5/from:refs/remotes/origin/PR-5 # timeout=10
 > git config remote.origin.url https://*****.com/scm/~ilakhtenkov/ilakhtenkov_test.git # timeout=10
...
```
**Expected behavior**:
lightweight checkout used

Downgrade to 2.9.5 resolves the problem.

**Comment by sams-gleb** [comment]
> Hi @bitwiseman Did you test your changes on BitBucket version 6. Because I'm experiencing following:
> **BitBucket version**: Atlassian Bitbucket v6.10.7
> **Jenkins Master**: 2.249.1
> **cloudbees-bitbucket-branch-source**: 2.9.6
> **Actual behavior**:
> Falling back to heavyweight checkout without lightweight try
> 
> ```
> Started by user Lakhtenkov Igor
> Checking out git https://*****.com/scm/~user/test.git https://******.com/scm/~user/test.git into /var/jenkins_home/workspace/multibranch_test_PR-5@script to read Jenkinsfile
> The recommended git tool is: NONE
> using credential ********-****-****-****-************
> using credential ********-****-****-****-************
> Cloning the remote Git repository
> Cloning with configured refspecs honoured and without tags
> Cloning repository https://*****.com/scm/~user/test.git
>  > git init /var/jenkins_home/workspace/multibranch_test_PR-5@script # timeout=10
> Fetching upstream changes from https://******.com/scm/~user/test.git
>  > git --version # timeout=10
>  > git --version # 'git version 2.11.0'
> using GIT_ASKPASS to set credentials System User
>  > git fetch --no-tags --progress -- https://*****.com/scm/~user/test.git +refs/pull-requests/5/from:refs/remotes/origin/PR-5 # timeout=10
>  > git config remote.origin.url https://*****.com/scm/~user/test.git # timeout=10
> ...
> ```
> 
> **Expected behavior**:
> lightweight checkout used
> 
> Downgrade to 2.9.5 resolves the problem.

Checked with freshly installed BB 6.10.7, logs seem ok for me ```Branch indexing
Obtained Jenkinsfile from 8c3f14ea149bde50ea472d37b4a7a5332d5b20f6+e308ed8c2e052690a0925f6e159e286fe8b215c2```

do you have v6 in jenkins settings in 	`Server Version`

**Comment by Lakhtenkov-iv** [comment]
@sams-gleb Thank for pointing to that. I didn't know about that setting.
